### ISSUE TITLE
VNA testing

### ISSUE THREAD

**Issue by Tyler-Ward** [SUWS/mast-planning#19]
###### Dependencies:
- [ ] Various cables need to be purposed #8
- [ ] and connectors attached #9 
###### Subtasks
- [X] VNA test FM dipole 
- [ ] VNA test 2m beam antenna
- [ ] VNA test 868 antenna
- [ ] VNA test triband
- [ ] VNA test hf dipole
- [ ] VNA test 70cm antenna(requires #15 )
- [ ] VNA test RF cabling
