### ISSUE TITLE
Test assemble mast hardware

### ISSUE THREAD

**Issue by Tyler-Ward** [SUWS/mast-planning#41]
Dependencies
- [ ] All mast hardware
- [ ] HF dipole refurbishment #14 
- [ ] 70cm antenna #15  
- [ ] Finish CAD designs of mounting hardware #1 
- [ ] Documentation for mast construction #2

Tasks
- [ ] perform Assembly of parts according to instructions.
- [ ] Amend instructions if any errors are spotted
