### ISSUE TITLE
Acquire planning permission for Mast

### ISSUE THREAD

**Issue by Tyler-Ward** [SUWS/mast-planning#46]
We will need planning permission for the mast
##### Prequisites
- [ ] #45 Determine new mast location
- [ ] #4 Get Permission from SUSU for mast
- [ ] #5 Get permission from E&F
